### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by SuGotLand**
add zh_CN

### CODE REVIEW

**Comment by sixpounder** [comment]
I assume this is related to https://github.com/sixpounder/game-of-life/pull/20
Is there a reason these are two separated PRs?

**Comment by SuGotLand** [comment]
> I assume this is related to #20 Is there a reason these are two separated PRs?

I'm not familiar with github.  In gitlab this generates a single request, I don't understand why it generates two separate requests in github.

**Comment by sixpounder** [comment]
Could you please make a single PR with both changes included? Thanks

**Comment by SuGotLand** [comment]
> Could you please make a single PR with both changes included? Thanks

I have made an new pull request, with two commits.

**Pull request closed without merging**
